{"name": "test_login_valid", "status": "broken", "statusDetails": {"message": "AttributeError: module 'configs.settings' has no attribute 'PW_TIMEOUT'", "trace": "page = <Page url='about:blank'>, test_users = {'editor': {'email': 'editor@example.com', 'password': 'P@ssw0rd'}, 'viewer': {'email': 'viewer@example.com', 'password': 'P@ssw0rd'}}\n\n    @pytest.mark.ui\n    @pytest.mark.auth\n    @pytest.mark.smoke\n    @allure.feature(\"Auth\")\n    @allure.story(\"Login\")\n    def test_login_valid(page, test_users):\n>       pg = AuthPage(page)\n\ntests\\auth\\test_login_valid.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <pages.auth_page.AuthPage object at 0x0000022AA3189A30>, page = <Page url='about:blank'>\n\n    def __init__(self, page: Page):\n        self.page: Page = page\n>       self.page.set_default_timeout(settings.PW_TIMEOUT)\nE       AttributeError: module 'configs.settings' has no attribute 'PW_TIMEOUT'\n\npages\\base_page.py:24: AttributeError"}, "start": 1756045329256, "stop": 1756045329256, "uuid": "16769130-0ec4-4539-869a-a9d25086d3a9", "historyId": "f370b6ae400907e33b53daf29861cd3c", "testCaseId": "f370b6ae400907e33b53daf29861cd3c", "fullName": "tests.auth.test_login_valid#test_login_valid", "labels": [{"name": "story", "value": "Login"}, {"name": "feature", "value": "Auth"}, {"name": "tag", "value": "smoke"}, {"name": "tag", "value": "auth"}, {"name": "tag", "value": "ui"}, {"name": "parentSuite", "value": "tests.auth"}, {"name": "suite", "value": "test_login_valid"}, {"name": "host", "value": "Thanh-PC"}, {"name": "thread", "value": "20604-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.auth.test_login_valid"}]}